server:
  port: 3333
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xmac?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: thread
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug