server:
  servlet:
    context-path: /xmi

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  freemarker:
    template-loader-path: classpath:/tpl
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .html
    cache: false